parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: ergometrix
    database_user: ergo
    database_password: ergo
    mailer_transport: gmail
    mailer_auth_mode: ~
    mailer_host: ~
    mailer_user: ergo
    mailer_password: ergo
    mailer_port: '465'
    locale: fr
    secret: 85ec8ed10dc3cbcc5bb57d69ec8f3c1051
    database_path: null
