<?php

namespace Xaj\ErgoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatRepository extends EntityRepository
{
    /**
     * 
     */
    public function getBoatsNotDeleted()
    {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.deleted = 0')
                ->orderBy('b.category', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * 
     */
    public function getDeletedBoats()
    {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.deleted = 1')
                ->orderBy('b.category', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * 
     */
    public function getBoatsNames()
    {
        $qb = $this->createQueryBuilder('b')->select('b.name');

        return $qb->getQuery()->getResult();
    }

    /**
     * 
     */
    public function countTotal()
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countNotDeleted()
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->where('b.deleted = false')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countValid()
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->where('b.deleted = false')
                    ->andWhere('b.valid = true')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countPayed()
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->where('b.deleted = false')
                    ->andWhere('b.payment = true')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countNotRecorded()
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->where('b.deleted = false')
                    ->andWhere('b.record = 0')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countByCategory($category)
    {
        return $this->createQueryBuilder('b')
                    ->select('COUNT(b)')
                    ->where('b.category = :cat')
                    ->setParameter('cat', $category)
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
